Add `tribal_land_percent`
down-ballot-climate-partners/deployment-gap-model pull request #276
Opened 2023-05-04 20:19 UTC by bendnorman

This PR adds a `tribal_land_percent` column to the county_fips and county_wide and county_long tables which is the percent of the county within tribal land.

@TrentonBush I'm a little confused about adding the column to the data mart tables. Seems like there is a lot of columns adding and dropping happening.

2023-05-05 00:02 UTC, TrentonBush requested changes

2023-05-06 03:16 UTC, bendnorman commented on src/dbcp/etl.py
> +    fips = dbcp.extract.fips_tables.extract()
Ah good point. I forgot that we'll probably need to update this data!

2023-05-06 03:16 UTC, bendnorman commented on src/dbcp/metadata/data_mart.py
> +        CheckConstraint("tribal_land_percent >= 0.0 AND tribal_land_percent <= 1.0"),
Groovy!

2023-05-06 03:16 UTC, bendnorman commented on src/dbcp/transform/fips_tables.py
> +    counties["tribal_land_percent"] = counties.tribal_land_percent.mask(
Good call. Added `raw_tribal_land_frac`.

2023-05-06 03:17 UTC, bendnorman commented on src/dbcp/transform/fips_tables.py
> +    counties["tribal_land_percent"] = (
updated 👍

2023-05-08 18:43 UTC, merged